title: Mitch Talmadge
email: contact@mitchtalmadge.com
description: Personal Blog & Portfolio
baseurl: ""
url: "https://mitchtalmadge.com"
github_username: mitchtalmadge
linkedin_username: mitchtalmadge

theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-sitemap

minima: # https://github.com/jekyll/minima
  skin: auto
  nav_pages:
    - index.md

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
