title: Mitch Talmadge
email: contact@mitchtalmadge.com
description: Personal Blog & Portfolio
baseurl: ""
url: "https://mitchtalmadge.com"
google_analytics: G-RSXJRNXKJV

github_username: mitchtalmadge
linkedin_username: mitchtalmadge

theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-sitemap

minima: # https://github.com/jekyll/minima
  skin: auto
  nav_pages:
    - index.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

comments:
  giscus:
    repo: MitchTalmadge/MitchTalmadge
    repo_id: MDEwOlJlcG9zaXRvcnkzMjc1MzYxNzQ=
    category: Post Comments
    category_id: DIC_kwDOE4XOLs4CoXx7
    mapping: og:title
    reactions_enabled: 1
    theme: preferred_color_scheme

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/